version: '3.8'
services:
  # PostgreSQL Master
  postgres_primary:
    image: bitnami/postgresql:14
    container_name: apuestas_postgres_primary
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres_password
      - POSTGRESQL_DATABASE=apuestas_db
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replicator_password
    volumes:
      - primary_data:/bitnami/postgresql

  # PostgreSQL Replica (Slave)
  postgres_replica:
    image: bitnami/postgresql:14
    container_name: apuestas_postgres_replica
    restart: always
    depends_on:
      - postgres_primary
    ports:
      - "5433:5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres_password
      - POSTGRESQL_MASTER_HOST=postgres_primary
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replicator_password
    volumes:
      - replica_data:/bitnami/postgresql

  # MySQL 
  mysql:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password 
    container_name: apuestas_mysql
    restart: always
    environment:
      MYSQL_DATABASE: apuestas_db
      MYSQL_ROOT_PASSWORD: mysql_password
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # ===== MONGODB SHARDING SETUP (MÍNIMO) =====
  
  # Config Server (1 solo para mínimo)
  mongo_configsvr:
    container_name: mongo_configsvr
    hostname: mongo_configsvr
    image: mongo:6.0
    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port 27019 --bind_ip_all
    volumes:
      - mongo_config1:/data/db
    networks:
      - mongo-network

  # Shard 1 (1 solo nodo para mínimo)
  mongo_shard1:
    container_name: mongo_shard1
    hostname: mongo_shard1
    image: mongo:6.0
    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port 27018 --bind_ip_all
    volumes:
      - mongo_shard1:/data/db
    networks:
      - mongo-network

  # Shard 2 (1 solo nodo para mínimo)
  mongo_shard2:
    container_name: mongo_shard2
    hostname: mongo_shard2
    image: mongo:6.0
    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port 27018 --bind_ip_all
    volumes:
      - mongo_shard2:/data/db
    networks:
      - mongo-network

  # Mongos Router (punto de entrada principal)
  mongo_router:
    container_name: mongo_router
    hostname: mongo_router
    image: mongo:6.0
    depends_on:
      - mongo_configsvr
      - mongo_shard1  
      - mongo_shard2
    command: mongos --configdb mongors1conf/mongo_configsvr:27019 --port 27017 --bind_ip_all
    ports:
      - "27017:27017"
    networks:
      - mongo-network

  # Redis Cache
  redis:
    image: redis:7.0-alpine
    container_name: apuestas_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  ## Etl
  apuestas_etl:
    image: bitnami/postgresql:14
    container_name: apuestas_postgres_etl
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRESQL_USERNAME=etl_user
      - POSTGRESQL_PASSWORD=etl_password
      - POSTGRESQL_DATABASE=etl_db
    volumes:
      - etl_data:/bitnami/postgresql

volumes:
  primary_data:
  replica_data:
  mysql_data:
  mongo_config1:
  mongo_shard1:
  mongo_shard2:
  redis_data:
  etl_data:

networks:
  mongo-network:
    driver: bridge
