version: '3.8'

services:
  # PostgreSQL Master
  postgres_primary:
    image: bitnami/postgresql:14
    container_name: apuestas_postgres_primary
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres_password
      - POSTGRESQL_DATABASE=apuestas_db
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replicator_password
    volumes:
      - primary_data:/bitnami/postgresql

  # PostgreSQL Replica (Slave)
  postgres_replica:
    image: bitnami/postgresql:14
    container_name: apuestas_postgres_replica
    restart: always
    depends_on:
      - postgres_primary
    ports:
      - "5433:5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres_password
      - POSTGRESQL_MASTER_HOST=postgres_primary
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replicator_password
    volumes:
      - replica_data:/bitnami/postgresql

  # MySQL 
  mysql:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password 
    container_name: apuestas_mysql
    restart: always
    environment:
      MYSQL_DATABASE: apuestas_db
      MYSQL_ROOT_PASSWORD: mysql_password
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


  # MongoDB 
  mongodb:
    image: mongo:6.0
    container_name: apuestas_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Redis Cache
  redis:
    image: redis:7.0-alpine
    container_name: apuestas_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  primary_data:
  replica_data:
  mysql_data:
  mongo_data:
  redis_data:
